openapi: 3.0.1
info:
  title: Swagger Blog
  description:
    "Ejemplo de API documentada\
    \     con Swagger [http://swagger.io](http://swagger.io) \""
  termsOfService: http://swagger.io/terms/
  contact:
    email: prueba@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers: 
  - url: http://localhost:3015/api/v2
tags:
  - name: comment
    description: Todo sobre el blog y sus comentarios (posts)
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /comentarios/json:
    get:
      tags:
        - comment
      summary: Obtener comentarios
      description: Obtener todos los comentarios en formato JSON
      operationId: findAllComments
      parameters:
      
